name: Application Deployment

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - name: Deploy application
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}

          script: |
            cd "${{ secrets.APPLICATION_PATH }}"
            source venv/bin/activate
            python -m pip install -r requirements.txt
            # Update application
            git pull origin main

            # Run database migrations
            python scripts/migrate.py

            # Restart application service
            sudo systemctl restart tournamenthub
