name: Application Deployment

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Check HOST
        env:
          DEPLOY_HOST: ${{ secrets.HOST }}
        run: |
          if [ -z "$DEPLOY_HOST" ]; then
            echo "HOST is leeg"
            exit 1
          else
            echo "HOST is ingesteld"
          fi
      - name: Deploy application
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}

          script: |
            cd "${{ secrets.APPLICATION_PATH }}"

            # Update application
            git pull origin main

            # Run database migrations
            python scripts/migrate.py

            # Restart application service
            sudo systemctl restart tournamenthub
